### PR TITLE
New Relic installation

### PR DESCRIPTION
**Pull request by FTgremlin**
-[x] Adding `New Relic` to Lantern to enable better performance testing and statistics

### CODE REVIEW

**Comment by radiodario** [comment]
looks good once the tests pass.

**Comment by radiodario** [comment]
actually it' doesn't look good - you can't use new relic with iso apps so you should check if it's the browser. put the newrelic on the client entry point https://discuss.newrelic.com/t/node-agent-fails-with-webpack/24874

**Comment by FTgremlin** [comment]
Looks like this passed!

**Comment by radiodario** [comment]
giphy 1

**Pull request merged**
