### PR TITLE
topics published vs read uses not_analyzed field

### PR DESCRIPTION
**Pull request by katsuraku**
screen shot 2015-11-30 at 16 41 16

### CODE REVIEW

**Comment by katsuraku** [comment]
card says in topic view as well as section view but none of the data in topic view is showing up with the strange 'in' or 'of' etc words.
NB the format of the reverse x axis column titles will need to be fixed up as they're overlapping.

**Comment by StuartFT** [comment]
seems like an unexpected side effect is that this introduces a bug making the titles unreadable on the charts?

**Comment by radiodario** [comment]
So i think this change (data wise) is not correct, as now the entire field is not being analysed, while we'd want to join by topic, now we're joining by topic array, which is not what we want...

**Comment by radiodario** [comment]
so this should be closed right?

**Comment by katsuraku** [comment]
yuss

**Pull request closed without merging**
