### PR TITLE
Add social referrers bar chart

### PR DESCRIPTION
**Pull request by radiodario**
shot

### CODE REVIEW

**Comment by jonathan-best** [comment]
giphy

**Comment by peter-mouland** [comment]
can only see 'acebook' :rotating_light: 
screen shot 2015-10-08 at 10 53 01 am

**Comment by radiodario** [comment]
i've reported the bug to c3 and added an interim solution (sorting the longest name first)

https://github.com/masayuki0812/c3/issues/129#issuecomment-146489222

**Comment by peter-mouland** [comment]
cool

**Pull request merged**
