### PR TITLE
Removes unwanted date-range options in article view

### PR DESCRIPTION
**Pull request by katsuraku**

### CODE REVIEW

**Comment by jonathan-best** [comment]
Awesome, were there no tests to tweak?

**Comment by katsuraku** [comment]
no tests affected. the unit tests and functional tests only really test the type of component rendered/its position, not the details of what the date range options are.

**Comment by jonathan-best** [comment]
Shamazing

**Comment by jonathan-best** [comment]
Y u no merge?

**Comment by katsuraku** [comment]
oh yep, merging now!

**Pull request merged**
