### PR TITLE
Add the retention table to the highlights page

### PR DESCRIPTION
**Pull request by jonathan-best**
* Add the query / esquery / aggreagtion
* Update ESClient to use an msearch for highlights
* Update the table formatter code to be a little more flexible - one large formatting function wasnt required
* Update the search component to use the new table formatter functions
* Update the highlights page to use the new table functions
* Add the new retention table to the page

### CODE REVIEW

**Comment by radiodario** [comment]
why is one of the files called `src/shared/utils/temp.js`? maybe you forgot to delete it or something? if not, we need a more informative name... to me temp means temporal, delete me, etc.

**Comment by radiodario** [comment]
Still, it looks good!

**Comment by jonathan-best** [comment]
How did i forget that! thanks temp file is no more :smile:

**Comment by Lucas-Gluchowski** [comment]
:+1:  for the query

**Pull request merged**
