### PR TITLE
Search tip only appears when there is text in the search box

### PR DESCRIPTION
**Pull request by katsuraku**

### CODE REVIEW

**Comment by radiodario** [comment]
I'm not sure now... i'd show it when the field `hasFocus` rather than when it has text.

you can check that with the DOM function `.hasFocus()`

**Comment by DanForys** [comment]
Should we close this PR but keep the branch for future use? It's been in limbo for over a month.

**Comment by katsuraku** [comment]
i guess 👍 @DanForys 
do i get to decide as author?

**Comment by DanForys** [comment]
Yes, you are hereby employed as the chief executive of the `tip-when-type` branch.

**Pull request closed without merging**
