### PR TITLE
Update React to 0.14...

### PR DESCRIPTION
**Pull request by i-like-robots**
... update react-intl to 2.0.0-beta, update react-bootstrap to 0.28.1 and update react-select to 0.9.1.

Updates React as per https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html

Updates to react-bootstrap and react-select to lesson number of warnings.

Required major version update to react-intl. This is a bit of a bodge job because their documentation is not up to date yet.

### CODE REVIEW

**Comment by radiodario** [comment]
looks good once the conflicts are resolved!

thank you so much for this!

**Comment by i-like-robots** [comment]
Rebased. Unit and functional tests are passing locally so not sure what's up with CI ¯\_(ツ)_/¯

screen shot 2015-12-11 at 15 49 57
screen shot 2015-12-11 at 15 50 19

**Comment by radiodario** [comment]
you had forgotten an Object.assign on Text.js. Object.assign is not supported on the version of chrome that circleci runs, so it was breaking.
this is now fixed

**Comment by i-like-robots** [comment]
:+1:

**Pull request merged**
