### PR TITLE
adds social referrers bar chart and breakdown table in new social section

### PR DESCRIPTION
**Pull request by katsuraku**
social breakdown is in defined list with some decent stylez

Styles for metric-list

WIP add unit test for MetricList component

Finished unit testing metric list component

Remove describe.only

### CODE REVIEW

**Comment by jonathan-best** [comment]
It could be useful to hook this into the single metric so that we can add comparators like in the interaction section. Its almost identical to this design but with a comparator.

**Comment by DanForys** [comment]
@jonathan-best I think we could easily add the comparator in the `<dd>` elements. Not sure we should put that in yet with no comparator requirement.

**Comment by jonathan-best** [comment]
@DanForys i was thinking that this could possibly replace the current How did the user interact solution, since they are so similar:

screen shot 2016-01-25 at 11 44 09

**Comment by katsuraku** [comment]
good idea, let's do it as a separate ticket and merge this one through?

**Comment by DanForys** [comment]
I concur with @katsuraku

**Pull request merged**
