### PR TITLE
percentages, percentages everywhere

### PR DESCRIPTION
**Pull request by radiodario**
image
Use percentages on all bar and column charts

- [x] Added option to use percentage data on bar charts
- [x] Add calculation function to `formatData` that creates percentages
- [x] change all sections to use percentages
- [x] Add percentage *and* raw value to tooltips
- [x] modify bar chart to go from 0 to 100

### CODE REVIEW

**Comment by peter-mouland** [comment]
nice work :+1:

**Comment by jonathan-best** [comment]
I noticed that a few of the bar charts dont always total 100% is that because we have a few hidden fields? or is it a rounding thing?

**Comment by radiodario** [comment]
rounding probably - do you have any concrete examples?

**Comment by jonathan-best** [comment]
The external sources total 98%:
http://ft-editorial-lantern-pr-167.herokuapp.com/articles/0049a468-4be5-11e5-b558-8a9722977189

**Comment by radiodario** [comment]
i could see how Math.flooring 4 things could make up 2%...

**Comment by peter-mouland** [comment]
...lets see if anyone else notice and if they care!?

**Comment by radiodario** [comment]
i'm making a fix

**Pull request merged**
