### PR TITLE
Date time

### PR DESCRIPTION
**Pull request by jonathan-best**
Update the Date picker for sections and topics

### CODE REVIEW

**Comment by radiodario** [comment]
screen shot 2015-11-17 at 16 09 33

nan nan, nan nan nan nan
nan batman

**Comment by jonathan-best** [comment]
What article and date range did you use? I haven't been able to reproduce this

**Comment by radiodario** [comment]
going from the results click on a section (so i suspect it's client side dates not being set?)

**Comment by FTgremlin** [comment]
http://localhost:3000/articles/8966bd12-73b3-11e5-a129-3fcc4f641d98/global/FT

screen shot 2015-11-18 at 10 37 43

**Comment by jonathan-best** [comment]
Updated the date picker to default to 30 days if no start value is provided - removes the Batman issue

**Comment by radiodario** [comment]
sweet
image

**Comment by jonathan-best** [comment]
Haha we need more batman gifs

**Pull request merged**
