### PR TITLE
search results now contain sections that are clickable

### PR DESCRIPTION
**Pull request by radiodario**
screen shot 2015-11-09 at 12 46 21

### CODE REVIEW

**Comment by jonathan-best** [comment]
anigif_enhanced-buzz-13939-1401896804-24

**Comment by radiodario** [comment]
hey @jonathan-best is that a yes or a no hahaha?

**Comment by jonathan-best** [comment]
A person on a unicycle ending in a blaze of glory can only be a :+1:

**Comment by radiodario** [comment]
point taken

**Pull request merged**
