### PR TITLE
Realtime article view to calculate time on page as 50th percentile ra…

### PR DESCRIPTION
**Pull request by DanForys**
…ther than average

For https://trello.com/c/BGbesaXu

### CODE REVIEW

**Comment by StuartFT** [comment]
I think aggregations/TopArticles.js needs updated too

**Comment by StuartFT** [comment]
Looked fine for me, the aggregation did take longer to run though... probably worth @FTgremlin running the perf tests on this one.

**Comment by FTgremlin** [comment]
@StuartFT probably good to talk to you about this. Perf tests had no issues.

Highlights tests:
[Pre-541](http://ftjen15725-lvpr-uk-p.osb.ft.com:8181/job/Lantern%20Performance%20Testing/116/artifact/results/req_page--pick-of-t-7a053.html)
[Post-541](http://ftjen15725-lvpr-uk-p.osb.ft.com:8181/job/Lantern%20Performance%20Testing/117/artifact/results/req_page--pick-of-t-7a053.html)

**Comment by DanForys** [comment]
Just to chime in with the "this feature wasn't about performance" card :tada:

**Comment by DanForys** [comment]
@StuartFT has :+1: this

**Pull request merged**
