### PR TITLE
Add Topic and Section Comparators

### PR DESCRIPTION
**Pull request by jonathan-best**
Add Topic Comparator
Add Section Comparator
Fix the NaN date picker
Fix the Section modifier desc
Styling Tweaks

### CODE REVIEW

**Comment by katsuraku** [comment]
i think line 105 of sectionModifier.js shd be `tags.push({label: this.props.query.topic, url : `topic/${this.props.query.topic}`}) : {};`
and then i'll find a gif

**Comment by jonathan-best** [comment]
@katsuraku Done :+1:

**Comment by katsuraku** [comment]
http://giphy.com/gifs/cheezburger-funny-golf-1jWiycvKwu8IE

**Comment by jonathan-best** [comment]
giphy

**Comment by katsuraku** [comment]
yes

**Pull request merged**
